# Generated by Django 4.2.10 on 2025-05-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_course_is_active_department_head_and_more'),
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.FloatField(help_text='Confidence level of the prediction (0-1)')),
                ('factors', models.JSONField(default=dict, help_text='Factors that influenced this prediction')),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this prediction has been applied to create an actual budget')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_predictions', to='core.academicyear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_predictions', to='budget.budgetcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_predictions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_predictions', to='core.department')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('department', 'academic_year', 'category')},
            },
        ),
    ]
