# Generated by Django 4.2.10 on 2025-05-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
    ]
